### ISSUE TITLE
Hashmask appearing in a non-password field

### ISSUE THREAD

**Issue by evajurman** [wyantb/HashMask#41]
In http://www.southparkstudios.com/full-episodes in the top left (absolute top left, except maybe a tab) there is a random hashmask that I'm pretty sure does not belong there. screenshot included below.
Computer Specs:
Netbook EeePC T101MT
Running FEDORA 17 (BETA)
Chrome 20.0.1132.17 beta

Extensions List (all enabled unless specified otherwise):
Alarm 0.60, Chroma 2.0.1, Cloudy Calculator 6.0.2, colorwheel 1.0.2, Docs PDF/PowerPoint Viewer (by Google) 3.9, Facebook Notifications 1.27, Google +1 Button 1.1.2.424, Google Dictionary (by Google) 3.0.12, Google Mail Checker 3.2, Google+ Notifications 1.0.1.424, HashMask 1.1, Python Shell 2.0.3, Reddit Enhancement Suite 4.1.2, snake 0.0.0.3, Turn Off the Lights 2.0.0.97, Vimium 1.32 (Disabled)

http://i.imgur.com/OGnw1.png

**Comment by wyantb** [comment]
Most likely, this has already been addressed for 1.2, thanks to a similar issue Kristen filed.  If you want to try it out now, it's this build here - https://github.com/wyantb/HashMask/raw/master/builds/hashmask-1.1.hotfix.crx

Otherwise, I'll see about actually getting version 1.2 done today.  We've only done a little bit of work on it, and I had some big ideas, so it's time to get them done.

**Comment by wyantb** [comment]
Hey Ethan,

Just pushed version 1.2 to the Chrome Web Store, the page should be updated soon.  When your version updates, would you be able to verify whether or not the issue is addressed?  Thanks!

**Comment by evajurman** [comment]
the new version fixed it! All is well!
